apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  ports:
    - name: http
      nodePort: 32107
      port: 3000
      protocol: TCP
      targetPort: http  
  selector:
    app: guestbook
    tier: frontend
